name: Step CI Action
author: Step CI
description: Run Step CI workflows
branding:
  icon: check-circle
  color: white
inputs:
  workflow:
    description: 'Workflow Path'
    required: true
    default: '.stepci/workflows/workflow.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workflow }}
